### Create a pet listing
POST http://localhost:3000/pets
Content-Type: application/json

{
    "name": "Buddy2",
    "price": 45000.00,
    "breed": "Golden Retriever",
    "slug": "buddy-golden-retriever1",
    "description": "Friendly and playful Golden Retriever, perfect for families.",
    "isAvailable": true,
    "city": "Dhaka",
    "address": "Dhanmondi, Dhaka",
    "images": ["https://example.com/images/buddy.jpg", "https://example.com/images/tom.jpg"],
    "age": 1.5
  }


### Get pets with filters
GET http://localhost:3000/pets?minPrice=20&breed=Golden Retriever&city=Dhaka

### Update pet listing
PATCH http://localhost:3000/pets/9b90cc0c-3b49-4b39-af72-785695daea77
Content-Type: application/json

{
  "price": 25000.00
}


### Delete a pet 
DELETE http://localhost:3000/pets/3859c4f3-a0ee-42c7-a59a-def8659182f3

