### Create a order for some pets
POST http://localhost:3000/orders
Content-Type: application/json

{
    "petIds": ["094b7158-d3ea-4d1c-84ca-ed5661d91e04"],
    "city": "Chittagong",
    "address": "12 Agrabad Commercial Area, Chittagong",
    "phoneNumber": "01712345678"
}